name: Build & Publish Docker Image with GHCR

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: AchieveClub.Server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/achieve_club_backend:latest
            ghcr.io/${{ github.repository_owner }}/achieve_club_backend:${{ github.run_number }}